require("dotenv").config();

module.exports = {

    PORT: process.env.PORT,
    DB_URL: process.env.MONGODB_URI,
    APP_SECRET: process.env.APP_SECRET,
    MESSAGE_BROKER_URL: process.env.MESSAGE_BROKER_URL,
    QUEUE_NAME: 'SHOPPING_QUEUE',
    EXCHANGE_NAME: 'ONLINE_SHOPPING',
    SHOPPING_BINDING_KEY: 'SHOPPING_SERVICE',
    PRODUCT_BINDING_KEY: 'PRODUCT_SERVICE',
    CUSTOMER_BINDING_KEY: 'CUSTOMER_SERVICE',
}
 